services:
  db:
    image: postgres:14.10-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql:rw
    ports:
      - 5432:5432
  admin:
    image: dpage/pgadmin4:7
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 5050:80

volumes:
  db_data:
